#!/bin/bash
# 🔍 COMPETITOR ANALYSIS AUTOMATION
# Analyzes all competitors for a project and generates benchmark report
# Called by: n8n workflow, manual, or scheduled cron

PROJECT_ID=$1
REGISTRY_FILE="$HOME/.claude/templates/universal-project-automation/PROJECT_REGISTRY.json"
REPORTS_DIR="$HOME/.claude/templates/universal-project-automation/reports"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

if [ -z "$PROJECT_ID" ]; then
  echo "❌ Usage: $0 <project-id>"
  exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 COMPETITOR ANALYSIS AUTOMATION"
echo "Project: $PROJECT_ID"
echo "Timestamp: $TIMESTAMP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if jq installed
if ! command -v jq &> /dev/null; then
  echo "❌ jq not installed. Installing..."
  brew install jq
fi

# Check if Playwright installed
if ! command -v playwright &> /dev/null; then
  echo "📦 Installing Playwright for screenshots..."
  npm install -g playwright
  npx playwright install chromium
fi

# Extract project data from registry
PROJECT_DATA=$(cat "$REGISTRY_FILE" | jq -r ".projects[] | select(.id == \"$PROJECT_ID\")")

if [ -z "$PROJECT_DATA" ]; then
  echo "❌ Project ID not found in registry: $PROJECT_ID"
  exit 1
fi

PROJECT_NAME=$(echo "$PROJECT_DATA" | jq -r '.name')
COMPETITORS=$(echo "$PROJECT_DATA" | jq -r '.competitors[]')

echo "📋 Project: $PROJECT_NAME"
echo "📊 Analyzing competitors..."
echo ""

mkdir -p "$REPORTS_DIR/$PROJECT_ID/competitors/$TIMESTAMP"
REPORT_DIR="$REPORTS_DIR/$PROJECT_ID/competitors/$TIMESTAMP"

# Initialize report
REPORT_FILE="$REPORT_DIR/analysis-report.md"
cat > "$REPORT_FILE" << EOF
# Competitor Analysis Report
**Project:** $PROJECT_NAME
**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Generated by:** Competitor Analysis Automation

---

## Competitors Analyzed

EOF

COMPETITOR_COUNT=$(echo "$PROJECT_DATA" | jq -r '.competitors | length')
echo "🔍 Found $COMPETITOR_COUNT competitors to analyze"
echo ""

# Analyze each competitor
COUNTER=1
echo "$PROJECT_DATA" | jq -c '.competitors[]' | while read -r competitor; do
  COMP_NAME=$(echo "$competitor" | jq -r '.name')
  COMP_URL=$(echo "$competitor" | jq -r '.url')

  echo "[$COUNTER/$COMPETITOR_COUNT] Analyzing: $COMP_NAME ($COMP_URL)"

  # Take screenshots
  echo "  📸 Taking screenshots..."
  mkdir -p "$REPORT_DIR/screenshots/$COMP_NAME"

  # Desktop screenshot
  npx playwright screenshot "$COMP_URL" \
    --viewport-size=1920,1080 \
    --full-page \
    --timeout=30000 \
    --output="$REPORT_DIR/screenshots/$COMP_NAME/desktop.png" 2>/dev/null

  # Mobile screenshot
  npx playwright screenshot "$COMP_URL" \
    --viewport-size=375,812 \
    --full-page \
    --timeout=30000 \
    --output="$REPORT_DIR/screenshots/$COMP_NAME/mobile.png" 2>/dev/null

  # Run Lighthouse audit
  echo "  🔦 Running Lighthouse audit..."
  if command -v lighthouse &> /dev/null; then
    lighthouse "$COMP_URL" \
      --output json \
      --output-path "$REPORT_DIR/lighthouse-$COMP_NAME.json" \
      --chrome-flags="--headless --no-sandbox" \
      --quiet 2>/dev/null

    # Extract scores
    if [ -f "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" ]; then
      PERF=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories.performance.score * 100')
      A11Y=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories.accessibility.score * 100')
      BP=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories["best-practices"].score * 100')
      SEO=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories.seo.score * 100')

      echo "  ✅ Lighthouse: Perf=$PERF A11y=$A11Y BP=$BP SEO=$SEO"
    fi
  else
    echo "  ⚠️  Lighthouse not installed, skipping"
  fi

  # Add to report
  cat >> "$REPORT_FILE" << COMP_EOF

### $COMP_NAME
- **URL:** $COMP_URL
- **Screenshots:** [Desktop](screenshots/$COMP_NAME/desktop.png) | [Mobile](screenshots/$COMP_NAME/mobile.png)
- **Lighthouse Scores:**
  - Performance: ${PERF:-N/A}/100
  - Accessibility: ${A11Y:-N/A}/100
  - Best Practices: ${BP:-N/A}/100
  - SEO: ${SEO:-N/A}/100

COMP_EOF

  ((COUNTER++))
  echo ""
done

# Generate comparison table
cat >> "$REPORT_FILE" << EOF

---

## Benchmark Comparison

| Competitor | Performance | Accessibility | Best Practices | SEO | Design Score |
|------------|-------------|---------------|----------------|-----|--------------|
EOF

echo "$PROJECT_DATA" | jq -c '.competitors[]' | while read -r competitor; do
  COMP_NAME=$(echo "$competitor" | jq -r '.name')
  DESIGN_SCORE=$(echo "$competitor" | jq -r '.benchmark_scores.design')
  FUNC_SCORE=$(echo "$competitor" | jq -r '.benchmark_scores.functionality')
  PRICE_SCORE=$(echo "$competitor" | jq -r '.benchmark_scores.price')

  # Read Lighthouse scores if available
  if [ -f "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" ]; then
    PERF=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories.performance.score * 100')
    A11Y=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories.accessibility.score * 100')
    BP=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories["best-practices"].score * 100')
    SEO=$(cat "$REPORT_DIR/lighthouse-$COMP_NAME.report.json" | jq -r '.categories.seo.score * 100')
  else
    PERF="N/A"
    A11Y="N/A"
    BP="N/A"
    SEO="N/A"
  fi

  echo "| $COMP_NAME | $PERF | $A11Y | $BP | $SEO | $DESIGN_SCORE |" >> "$REPORT_FILE"
done

# Add target requirements
cat >> "$REPORT_FILE" << EOF

---

## Target Requirements for $PROJECT_NAME

**3 Pillars Strategy:**

1. **Cost:** $(echo "$PROJECT_DATA" | jq -r '.target_pillars.cost')
2. **Functionality:** $(echo "$PROJECT_DATA" | jq -r '.target_pillars.functionality')
3. **Design:** $(echo "$PROJECT_DATA" | jq -r '.target_pillars.design')

**Lighthouse Targets:**
- Performance: $(echo "$PROJECT_DATA" | jq -r '.lighthouse_target.performance')/100
- Accessibility: $(echo "$PROJECT_DATA" | jq -r '.lighthouse_target.accessibility')/100
- Best Practices: $(echo "$PROJECT_DATA" | jq -r '.lighthouse_target.best_practices')/100
- SEO: $(echo "$PROJECT_DATA" | jq -r '.lighthouse_target.seo')/100

---

## Recommendations

Based on competitor analysis:

1. **Design Inspiration:** Study screenshots from top-rated competitors
2. **Performance Gaps:** Identify areas where competitors score higher
3. **Unique Features:** Differentiate with better functionality at lower cost
4. **Continuous Monitoring:** Re-run this analysis weekly/monthly

---

*Report generated by: Competitor Analysis Automation*
*Timestamp: $TIMESTAMP*
EOF

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ COMPETITOR ANALYSIS COMPLETE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Report: $REPORT_FILE"
echo "📸 Screenshots: $REPORT_DIR/screenshots/"
echo "🔦 Lighthouse reports: $REPORT_DIR/lighthouse-*.json"
echo ""

# Save latest report path to registry
LATEST_REPORT="$REPORT_DIR"
echo "$LATEST_REPORT" > "$REPORTS_DIR/$PROJECT_ID/latest-competitor-analysis.txt"

echo "💡 View report:"
echo "   open $REPORT_FILE"
echo ""
