#!/bin/bash
# ✅ VALIDATION 4 LAYERS - POST-VERIFICATION AUTOMATION
# Executes the 4 POST-verification layers before deployment
# Called by: n8n workflow, manual, or deploy-auto.sh

PROJECT_ID=$1
REGISTRY_FILE="$HOME/.claude/templates/universal-project-automation/PROJECT_REGISTRY.json"
REPORTS_DIR="$HOME/.claude/templates/universal-project-automation/reports"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

if [ -z "$PROJECT_ID" ]; then
  echo "❌ Usage: $0 <project-id>"
  exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ VALIDATION 4 LAYERS - POST-VERIFICATION"
echo "Project: $PROJECT_ID"
echo "Timestamp: $TIMESTAMP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Extract project data from registry
PROJECT_DATA=$(cat "$REGISTRY_FILE" | jq -r ".projects[] | select(.id == \"$PROJECT_ID\")")

if [ -z "$PROJECT_DATA" ]; then
  echo "❌ Project ID not found in registry: $PROJECT_ID"
  exit 1
fi

PROJECT_NAME=$(echo "$PROJECT_DATA" | jq -r '.name')
PROJECT_PATH=$(echo "$PROJECT_DATA" | jq -r '.path')
LIGHTHOUSE_TARGET=$(echo "$PROJECT_DATA" | jq -r '.lighthouse_target')

# Check if project path exists
if [ ! -z "$PROJECT_PATH" ] && [ "$PROJECT_PATH" != "null" ] && [ ! -d "$PROJECT_PATH" ]; then
  echo "❌ Project directory does not exist: $PROJECT_PATH"
  exit 1
fi

# Create validation report directory
mkdir -p "$REPORTS_DIR/$PROJECT_ID/validation/$TIMESTAMP"
VALIDATION_DIR="$REPORTS_DIR/$PROJECT_ID/validation/$TIMESTAMP"
REPORT_FILE="$VALIDATION_DIR/validation-report.md"

# Initialize report
cat > "$REPORT_FILE" << EOF
# Validation 4 Layers Report
**Project:** $PROJECT_NAME
**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Generated by:** Validation 4 Layers Automation

---

## Validation Layers

EOF

# Validation status trackers
LAYER1_PASS=0
LAYER2_PASS=0
LAYER3_PASS=0
LAYER4_PASS=0
ALL_LAYERS_PASS=0

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# LAYER 1: LIGHTHOUSE AUDIT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔦 LAYER 1: LIGHTHOUSE AUDIT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get target scores from registry
PERF_TARGET=$(echo "$LIGHTHOUSE_TARGET" | jq -r '.performance')
A11Y_TARGET=$(echo "$LIGHTHOUSE_TARGET" | jq -r '.accessibility')
BP_TARGET=$(echo "$LIGHTHOUSE_TARGET" | jq -r '.best_practices')
SEO_TARGET=$(echo "$LIGHTHOUSE_TARGET" | jq -r '.seo')

echo "📊 Target Scores:"
echo "   Performance: >$PERF_TARGET"
echo "   Accessibility: >$A11Y_TARGET"
echo "   Best Practices: >$BP_TARGET"
echo "   SEO: >$SEO_TARGET"
echo ""

# Check if Lighthouse is installed
if ! command -v lighthouse &> /dev/null; then
  echo "📦 Installing Lighthouse CLI..."
  npm install -g lighthouse
fi

# Determine URL to audit
# If project has deployment URL (from latest deployment), use that
# Otherwise, try to build and serve locally
AUDIT_URL=""

# Check for Vercel/Netlify deployment URL
if [ -f "$VALIDATION_DIR/../latest-deployment-url.txt" ]; then
  AUDIT_URL=$(cat "$VALIDATION_DIR/../latest-deployment-url.txt")
  echo "🌐 Using deployment URL: $AUDIT_URL"
elif [ ! -z "$PROJECT_PATH" ] && [ "$PROJECT_PATH" != "null" ]; then
  # Try to build and serve locally
  echo "🏗️  Building project locally for audit..."
  cd "$PROJECT_PATH" || exit 1

  # Build
  if [ -f "package.json" ]; then
    npm run build > /dev/null 2>&1 || echo "⚠️  Build failed, will try to audit dev server"

    # Start dev server in background (timeout after 60s if not ready)
    npm run dev > /dev/null 2>&1 &
    DEV_PID=$!

    # Wait for server to be ready (max 30s)
    for i in {1..30}; do
      if curl -s http://localhost:3000 > /dev/null 2>&1; then
        AUDIT_URL="http://localhost:3000"
        break
      fi
      sleep 1
    done

    if [ -z "$AUDIT_URL" ]; then
      echo "❌ Could not start local server for audit"
      kill $DEV_PID 2>/dev/null
      echo "ℹ️  Skipping Lighthouse audit (no URL available)"
      echo ""
      LAYER1_PASS=0
    fi
  else
    echo "❌ No package.json found, cannot build/serve project"
    LAYER1_PASS=0
  fi
else
  echo "⚠️  No project path or deployment URL, skipping Lighthouse"
  LAYER1_PASS=0
fi

# Run Lighthouse if we have a URL
if [ ! -z "$AUDIT_URL" ]; then
  echo "🔦 Running Lighthouse audit on $AUDIT_URL..."

  lighthouse "$AUDIT_URL" \
    --output json \
    --output html \
    --output-path "$VALIDATION_DIR/lighthouse" \
    --chrome-flags="--headless --no-sandbox" \
    --quiet 2>/dev/null

  if [ -f "$VALIDATION_DIR/lighthouse.report.json" ]; then
    # Extract scores
    PERF_SCORE=$(cat "$VALIDATION_DIR/lighthouse.report.json" | jq -r '.categories.performance.score * 100' | awk '{print int($1+0.5)}')
    A11Y_SCORE=$(cat "$VALIDATION_DIR/lighthouse.report.json" | jq -r '.categories.accessibility.score * 100' | awk '{print int($1+0.5)}')
    BP_SCORE=$(cat "$VALIDATION_DIR/lighthouse.report.json" | jq -r '.categories["best-practices"].score * 100' | awk '{print int($1+0.5)}')
    SEO_SCORE=$(cat "$VALIDATION_DIR/lighthouse.report.json" | jq -r '.categories.seo.score * 100' | awk '{print int($1+0.5)}')

    echo ""
    echo "📊 Lighthouse Results:"
    echo "   Performance: $PERF_SCORE/100 (target: >$PERF_TARGET)"
    echo "   Accessibility: $A11Y_SCORE/100 (target: >$A11Y_TARGET)"
    echo "   Best Practices: $BP_SCORE/100 (target: >$BP_TARGET)"
    echo "   SEO: $SEO_SCORE/100 (target: >$SEO_TARGET)"
    echo ""

    # Check if all scores meet targets
    if [ "$PERF_SCORE" -ge "$PERF_TARGET" ] && \
       [ "$A11Y_SCORE" -ge "$A11Y_TARGET" ] && \
       [ "$BP_SCORE" -ge "$BP_TARGET" ] && \
       [ "$SEO_SCORE" -ge "$SEO_TARGET" ]; then
      echo "✅ Layer 1: PASSED - All Lighthouse scores meet targets"
      LAYER1_PASS=1

      cat >> "$REPORT_FILE" << EOF
### ✅ Layer 1: Lighthouse Audit - PASSED

| Metric | Score | Target | Status |
|--------|-------|--------|--------|
| Performance | $PERF_SCORE | $PERF_TARGET | ✅ |
| Accessibility | $A11Y_SCORE | $A11Y_TARGET | ✅ |
| Best Practices | $BP_SCORE | $BP_TARGET | ✅ |
| SEO | $SEO_SCORE | $SEO_TARGET | ✅ |

📄 [Full Report](lighthouse.report.html)

EOF
    else
      echo "❌ Layer 1: FAILED - Some scores below target"
      LAYER1_PASS=0

      cat >> "$REPORT_FILE" << EOF
### ❌ Layer 1: Lighthouse Audit - FAILED

| Metric | Score | Target | Status |
|--------|-------|--------|--------|
| Performance | $PERF_SCORE | $PERF_TARGET | $([ "$PERF_SCORE" -ge "$PERF_TARGET" ] && echo "✅" || echo "❌") |
| Accessibility | $A11Y_SCORE | $A11Y_TARGET | $([ "$A11Y_SCORE" -ge "$A11Y_TARGET" ] && echo "✅" || echo "❌") |
| Best Practices | $BP_SCORE | $BP_TARGET | $([ "$BP_SCORE" -ge "$BP_TARGET" ] && echo "✅" || echo "❌") |
| SEO | $SEO_SCORE | $SEO_TARGET | $([ "$SEO_SCORE" -ge "$SEO_TARGET" ] && echo "✅" || echo "❌") |

📄 [Full Report](lighthouse.report.html)

**Action Required:** Improve scores to meet targets before deployment.

EOF
    fi
  else
    echo "❌ Lighthouse audit failed to generate report"
    LAYER1_PASS=0
  fi

  # Kill dev server if we started one
  if [ ! -z "$DEV_PID" ]; then
    kill $DEV_PID 2>/dev/null
  fi
fi

echo ""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# LAYER 2: WCAG AA COMPLIANCE CHECK
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "♿ LAYER 2: WCAG AA COMPLIANCE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if Pa11y is installed
if ! command -v pa11y &> /dev/null; then
  echo "📦 Installing Pa11y for accessibility testing..."
  npm install -g pa11y
fi

# Run Pa11y if we have a URL
if [ ! -z "$AUDIT_URL" ]; then
  echo "♿ Running WCAG AA compliance check..."

  # Start dev server again if needed (and killed earlier)
  if [ ! -z "$DEV_PID" ] && ! kill -0 $DEV_PID 2>/dev/null && [ ! -z "$PROJECT_PATH" ]; then
    cd "$PROJECT_PATH"
    npm run dev > /dev/null 2>&1 &
    DEV_PID=$!
    sleep 10  # Wait for server
    AUDIT_URL="http://localhost:3000"
  fi

  pa11y "$AUDIT_URL" \
    --standard WCAG2AA \
    --reporter json > "$VALIDATION_DIR/pa11y-report.json" 2>/dev/null

  if [ -f "$VALIDATION_DIR/pa11y-report.json" ]; then
    VIOLATIONS=$(cat "$VALIDATION_DIR/pa11y-report.json" | jq '. | length')

    echo ""
    echo "📊 WCAG AA Results:"
    echo "   Violations: $VIOLATIONS"
    echo ""

    if [ "$VIOLATIONS" -eq 0 ]; then
      echo "✅ Layer 2: PASSED - No WCAG AA violations"
      LAYER2_PASS=1

      cat >> "$REPORT_FILE" << EOF
### ✅ Layer 2: WCAG AA Compliance - PASSED

- **Violations:** 0
- **Standard:** WCAG 2.1 AA

Site is fully compliant with WCAG AA accessibility standards.

EOF
    else
      echo "❌ Layer 2: FAILED - $VIOLATIONS WCAG AA violations found"
      LAYER2_PASS=0

      # Extract top 3 violations
      TOP_VIOLATIONS=$(cat "$VALIDATION_DIR/pa11y-report.json" | jq -r '.[0:3] | .[] | "- " + .message' 2>/dev/null)

      cat >> "$REPORT_FILE" << EOF
### ❌ Layer 2: WCAG AA Compliance - FAILED

- **Violations:** $VIOLATIONS
- **Standard:** WCAG 2.1 AA

**Top Issues:**
$TOP_VIOLATIONS

📄 [Full Report](pa11y-report.json)

**Action Required:** Fix accessibility violations before deployment.

EOF
    fi
  else
    echo "⚠️  Pa11y report not generated, skipping"
    LAYER2_PASS=0
  fi

  # Kill dev server
  if [ ! -z "$DEV_PID" ]; then
    kill $DEV_PID 2>/dev/null
  fi
else
  echo "⚠️  No URL available, skipping WCAG check"
  LAYER2_PASS=0

  cat >> "$REPORT_FILE" << EOF
### ⚠️ Layer 2: WCAG AA Compliance - SKIPPED

No URL available for testing.

EOF
fi

echo ""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# LAYER 3: VISUAL REGRESSION TESTING
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📸 LAYER 3: VISUAL REGRESSION TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if Playwright is installed
if ! command -v playwright &> /dev/null; then
  echo "📦 Installing Playwright for screenshots..."
  npm install -g playwright
  npx playwright install chromium
fi

if [ ! -z "$AUDIT_URL" ]; then
  echo "📸 Taking screenshots for visual regression..."

  mkdir -p "$VALIDATION_DIR/screenshots"

  # Start dev server again if needed
  if [ ! -z "$DEV_PID" ] && ! kill -0 $DEV_PID 2>/dev/null && [ ! -z "$PROJECT_PATH" ]; then
    cd "$PROJECT_PATH"
    npm run dev > /dev/null 2>&1 &
    DEV_PID=$!
    sleep 10
    AUDIT_URL="http://localhost:3000"
  fi

  # Desktop screenshot
  npx playwright screenshot "$AUDIT_URL" \
    --viewport-size=1920,1080 \
    --full-page \
    --timeout=30000 \
    --output="$VALIDATION_DIR/screenshots/desktop-current.png" 2>/dev/null

  # Mobile screenshot
  npx playwright screenshot "$AUDIT_URL" \
    --viewport-size=375,812 \
    --full-page \
    --timeout=30000 \
    --output="$VALIDATION_DIR/screenshots/mobile-current.png" 2>/dev/null

  # Tablet screenshot
  npx playwright screenshot "$AUDIT_URL" \
    --viewport-size=768,1024 \
    --full-page \
    --timeout=30000 \
    --output="$VALIDATION_DIR/screenshots/tablet-current.png" 2>/dev/null

  echo "✅ Screenshots captured: desktop, mobile, tablet"

  # Check if baseline screenshots exist for comparison
  BASELINE_DIR="$REPORTS_DIR/$PROJECT_ID/baseline-screenshots"

  if [ -d "$BASELINE_DIR" ]; then
    echo "🔍 Comparing with baseline screenshots..."

    # Simple file size comparison (proper visual diff would need additional tools)
    DESKTOP_BASELINE_SIZE=$(stat -f%z "$BASELINE_DIR/desktop.png" 2>/dev/null || stat -c%s "$BASELINE_DIR/desktop.png" 2>/dev/null || echo "0")
    DESKTOP_CURRENT_SIZE=$(stat -f%z "$VALIDATION_DIR/screenshots/desktop-current.png" 2>/dev/null || stat -c%s "$VALIDATION_DIR/screenshots/desktop-current.png" 2>/dev/null || echo "0")

    SIZE_DIFF=$((DESKTOP_CURRENT_SIZE - DESKTOP_BASELINE_SIZE))
    SIZE_DIFF_ABS=${SIZE_DIFF#-}  # Absolute value
    SIZE_DIFF_PCT=0

    if [ "$DESKTOP_BASELINE_SIZE" -gt 0 ]; then
      SIZE_DIFF_PCT=$((SIZE_DIFF_ABS * 100 / DESKTOP_BASELINE_SIZE))
    fi

    echo ""
    echo "📊 Visual Regression Results:"
    echo "   Baseline size: $DESKTOP_BASELINE_SIZE bytes"
    echo "   Current size: $DESKTOP_CURRENT_SIZE bytes"
    echo "   Difference: ${SIZE_DIFF_PCT}%"
    echo ""

    # If difference < 10%, consider it PASSED (minor variations expected)
    if [ "$SIZE_DIFF_PCT" -lt 10 ]; then
      echo "✅ Layer 3: PASSED - Visual changes within acceptable range"
      LAYER3_PASS=1

      cat >> "$REPORT_FILE" << EOF
### ✅ Layer 3: Visual Regression - PASSED

- **Desktop Screenshot:** [View](screenshots/desktop-current.png)
- **Mobile Screenshot:** [View](screenshots/mobile-current.png)
- **Tablet Screenshot:** [View](screenshots/tablet-current.png)
- **Visual Change:** ${SIZE_DIFF_PCT}% (within acceptable 10% threshold)

No significant visual regressions detected.

EOF
    else
      echo "⚠️  Layer 3: WARNING - Significant visual changes detected (${SIZE_DIFF_PCT}%)"
      LAYER3_PASS=1  # Still pass but warn

      cat >> "$REPORT_FILE" << EOF
### ⚠️ Layer 3: Visual Regression - WARNING

- **Desktop Screenshot:** [View](screenshots/desktop-current.png)
- **Mobile Screenshot:** [View](screenshots/mobile-current.png)
- **Tablet Screenshot:** [View](screenshots/tablet-current.png)
- **Visual Change:** ${SIZE_DIFF_PCT}% (exceeds 10% threshold)

**Action Recommended:** Review screenshots manually to ensure changes are intentional.

EOF
    fi
  else
    echo "ℹ️  No baseline screenshots found, saving current as baseline..."
    mkdir -p "$BASELINE_DIR"
    cp "$VALIDATION_DIR/screenshots/desktop-current.png" "$BASELINE_DIR/desktop.png"
    cp "$VALIDATION_DIR/screenshots/mobile-current.png" "$BASELINE_DIR/mobile.png"
    cp "$VALIDATION_DIR/screenshots/tablet-current.png" "$BASELINE_DIR/tablet.png"

    echo "✅ Layer 3: PASSED - Baseline screenshots created"
    LAYER3_PASS=1

    cat >> "$REPORT_FILE" << EOF
### ✅ Layer 3: Visual Regression - BASELINE CREATED

- **Desktop Screenshot:** [View](screenshots/desktop-current.png)
- **Mobile Screenshot:** [View](screenshots/mobile-current.png)
- **Tablet Screenshot:** [View](screenshots/tablet-current.png)

Baseline screenshots saved for future comparisons.

EOF
  fi

  # Kill dev server
  if [ ! -z "$DEV_PID" ]; then
    kill $DEV_PID 2>/dev/null
  fi
else
  echo "⚠️  No URL available, skipping visual regression"
  LAYER3_PASS=0

  cat >> "$REPORT_FILE" << EOF
### ⚠️ Layer 3: Visual Regression - SKIPPED

No URL available for testing.

EOF
fi

echo ""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# LAYER 4: DESIGN SYSTEM COMPLIANCE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎨 LAYER 4: DESIGN SYSTEM COMPLIANCE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Design system checks (if project path exists)
if [ ! -z "$PROJECT_PATH" ] && [ "$PROJECT_PATH" != "null" ] && [ -d "$PROJECT_PATH" ]; then
  cd "$PROJECT_PATH"

  echo "🎨 Checking design system compliance..."

  DESIGN_VIOLATIONS=0
  DESIGN_CHECKS=""

  # Check 1: Tailwind config exists
  if [ -f "tailwind.config.js" ] || [ -f "tailwind.config.ts" ]; then
    echo "   ✅ Tailwind CSS config found"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ✅ Tailwind CSS configuration present"
  else
    echo "   ⚠️  No Tailwind config found"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ⚠️ No Tailwind CSS configuration"
    ((DESIGN_VIOLATIONS++))
  fi

  # Check 2: Typography scale compliance (check for hardcoded font sizes)
  HARDCODED_SIZES=$(grep -r "font-size:" src/ 2>/dev/null | grep -v "node_modules" | wc -l | tr -d ' ')
  if [ "$HARDCODED_SIZES" -eq 0 ]; then
    echo "   ✅ No hardcoded font sizes (using Tailwind classes)"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ✅ Typography: Using Tailwind scale (no hardcoded sizes)"
  else
    echo "   ⚠️  Found $HARDCODED_SIZES hardcoded font-size declarations"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ⚠️ Typography: $HARDCODED_SIZES hardcoded font-size found (should use Tailwind)"
    ((DESIGN_VIOLATIONS++))
  fi

  # Check 3: Color system (check for hardcoded colors)
  HARDCODED_COLORS=$(grep -r "#[0-9a-fA-F]\{6\}" src/ 2>/dev/null | grep -v "node_modules" | wc -l | tr -d ' ')
  if [ "$HARDCODED_COLORS" -lt 5 ]; then
    echo "   ✅ Minimal hardcoded colors (using design tokens)"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ✅ Colors: Using design tokens ($HARDCODED_COLORS hardcoded)"
  else
    echo "   ⚠️  Found $HARDCODED_COLORS hardcoded color values"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ⚠️ Colors: $HARDCODED_COLORS hardcoded values (should use Tailwind tokens)"
    ((DESIGN_VIOLATIONS++))
  fi

  # Check 4: Spacing consistency (check for arbitrary values)
  ARBITRARY_SPACING=$(grep -r "\[.*px\]" src/ 2>/dev/null | grep -v "node_modules" | wc -l | tr -d ' ')
  if [ "$ARBITRARY_SPACING" -lt 10 ]; then
    echo "   ✅ Minimal arbitrary spacing values"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ✅ Spacing: Using Tailwind scale ($ARBITRARY_SPACING arbitrary values)"
  else
    echo "   ⚠️  Found $ARBITRARY_SPACING arbitrary spacing values"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ⚠️ Spacing: $ARBITRARY_SPACING arbitrary values (should use Tailwind scale)"
    ((DESIGN_VIOLATIONS++))
  fi

  # Check 5: Component structure (Radix UI usage for accessibility)
  if grep -q "@radix-ui" package.json 2>/dev/null; then
    echo "   ✅ Using Radix UI for accessible components"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ✅ Components: Radix UI found (accessible primitives)"
  else
    echo "   ⚠️  Radix UI not found (recommend for accessibility)"
    DESIGN_CHECKS="$DESIGN_CHECKS\n- ⚠️ Components: Consider adding Radix UI for accessibility"
    # Not counting as violation, just recommendation
  fi

  echo ""
  echo "📊 Design System Results:"
  echo "   Violations: $DESIGN_VIOLATIONS"
  echo ""

  if [ "$DESIGN_VIOLATIONS" -eq 0 ]; then
    echo "✅ Layer 4: PASSED - Design system compliant"
    LAYER4_PASS=1

    cat >> "$REPORT_FILE" << EOF
### ✅ Layer 4: Design System Compliance - PASSED

**Compliance Checks:**
$(echo -e "$DESIGN_CHECKS")

Design system is well-structured and follows best practices.

EOF
  elif [ "$DESIGN_VIOLATIONS" -lt 3 ]; then
    echo "⚠️  Layer 4: WARNING - Minor design system issues ($DESIGN_VIOLATIONS)"
    LAYER4_PASS=1  # Still pass but warn

    cat >> "$REPORT_FILE" << EOF
### ⚠️ Layer 4: Design System Compliance - WARNING

**Compliance Checks:**
$(echo -e "$DESIGN_CHECKS")

Minor issues found. Recommended to fix for consistency.

EOF
  else
    echo "❌ Layer 4: FAILED - Significant design system violations ($DESIGN_VIOLATIONS)"
    LAYER4_PASS=0

    cat >> "$REPORT_FILE" << EOF
### ❌ Layer 4: Design System Compliance - FAILED

**Compliance Checks:**
$(echo -e "$DESIGN_CHECKS")

**Action Required:** Refactor to follow design system standards before deployment.

EOF
  fi
else
  echo "⚠️  No project path, skipping design system check"
  LAYER4_PASS=0

  cat >> "$REPORT_FILE" << EOF
### ⚠️ Layer 4: Design System Compliance - SKIPPED

No project path available for checking.

EOF
fi

echo ""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FINAL VALIDATION RESULT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 FINAL VALIDATION RESULT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Calculate pass/fail
LAYERS_PASSED=$((LAYER1_PASS + LAYER2_PASS + LAYER3_PASS + LAYER4_PASS))

echo "Layers Summary:"
echo "   Layer 1 (Lighthouse): $([ "$LAYER1_PASS" -eq 1 ] && echo "✅ PASSED" || echo "❌ FAILED")"
echo "   Layer 2 (WCAG AA): $([ "$LAYER2_PASS" -eq 1 ] && echo "✅ PASSED" || echo "❌ FAILED")"
echo "   Layer 3 (Visual Regression): $([ "$LAYER3_PASS" -eq 1 ] && echo "✅ PASSED" || echo "❌ FAILED")"
echo "   Layer 4 (Design System): $([ "$LAYER4_PASS" -eq 1 ] && echo "✅ PASSED" || echo "❌ FAILED")"
echo ""
echo "Total: $LAYERS_PASSED/4 layers passed"
echo ""

# Determine if deployment should proceed
if [ "$LAYERS_PASSED" -eq 4 ]; then
  ALL_LAYERS_PASS=1
  echo "✅ ALL VALIDATION LAYERS PASSED"
  echo "🚀 Project is ready for deployment"

  cat >> "$REPORT_FILE" << EOF

---

## ✅ VALIDATION RESULT: PASSED

**All 4 layers passed successfully.**

✅ Project meets all quality gates and is ready for production deployment.

- Lighthouse scores meet targets
- WCAG AA compliant
- No visual regressions
- Design system compliant

**Next Steps:**
1. Run \`deploy-auto.sh $PROJECT_ID\` to deploy to production
2. Monitor post-deployment metrics
3. Update baseline screenshots if intentional changes

---

*Report generated by: Validation 4 Layers Automation*
*Timestamp: $TIMESTAMP*
EOF

  EXIT_CODE=0
elif [ "$LAYERS_PASSED" -ge 3 ]; then
  echo "⚠️  VALIDATION WARNING: $LAYERS_PASSED/4 layers passed"
  echo "🔍 Review issues before deployment (deployment allowed with caution)"

  cat >> "$REPORT_FILE" << EOF

---

## ⚠️ VALIDATION RESULT: WARNING

**$LAYERS_PASSED/4 layers passed.**

⚠️ Some quality gates have warnings or failures. Review before deployment.

**Recommended Actions:**
1. Review failed layer(s) above
2. Fix critical issues
3. Re-run validation: \`validation-4layers.sh $PROJECT_ID\`
4. Deploy with caution if issues are non-critical

---

*Report generated by: Validation 4 Layers Automation*
*Timestamp: $TIMESTAMP*
EOF

  EXIT_CODE=1
else
  ALL_LAYERS_PASS=0
  echo "❌ VALIDATION FAILED: Only $LAYERS_PASSED/4 layers passed"
  echo "🚫 Project is NOT ready for deployment"

  cat >> "$REPORT_FILE" << EOF

---

## ❌ VALIDATION RESULT: FAILED

**Only $LAYERS_PASSED/4 layers passed.**

❌ Project does NOT meet quality gates. **Deployment blocked.**

**Required Actions:**
1. Fix issues in failed layers (see above)
2. Re-run validation: \`validation-4layers.sh $PROJECT_ID\`
3. All 4 layers must pass before deployment

---

*Report generated by: Validation 4 Layers Automation*
*Timestamp: $TIMESTAMP*
EOF

  EXIT_CODE=2
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📄 Validation Report: $REPORT_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Save validation result for deploy script
echo "$ALL_LAYERS_PASS" > "$VALIDATION_DIR/validation-result.txt"

exit $EXIT_CODE
